// ============================================================
// config.js — Variables globales, datos de configuración,
//             plantillas de factura, idiomas, colores ruleta
// ============================================================

// --- Variables Globales ---
        let db;
        let compras = [], logistica = [], inversionExtras = 0, cuentasGeneradas = [];
        let editIndex = -1, editCompraIndex = -1;
        let participantes = [], rifaCompras = [];
        let resumenMarcado = {}, resumenManualOverrides = {}, manualMarkCount = {};
        let ultimoProductoSeleccionado = null, logoHeader = '', idiomaActual = 'es';
        let isDarkMode = localStorage.getItem('darkMode') === 'true';
        let debounceTimer;
        let graficoVentas = null, graficoVentasDashboard = null, graficoVentasPorDia = null, graficoTopProductos = null, graficoTopCompradores = null;
        let temaActual = localStorage.getItem('tema') || 'default';
        let deferredPrompt;
        let backupInterval = null;
        let backupAutoActivo = localStorage.getItem('backupAutoActivo') === 'true';
        let backupIntervalMinutos = parseInt(localStorage.getItem('backupIntervalMinutos')) || 5;
        let selectedTemplate = localStorage.getItem('selectedTemplate') || 'plantilla1';
        let secuenciaFactura = localStorage.getItem('secuenciaFactura') || 'FACT-';
        let numeroFacturaActual = parseInt(localStorage.getItem('numeroFacturaActual')) || 1;
        let ruletaColorCompartidas = localStorage.getItem('ruletaColorCompartidas') || '#2563b0';
        let ruletaColorCompras = localStorage.getItem('ruletaColorCompras') || '#059669';
        let selectedAutocompleteIndex = -1;
        let lastSelectedProduct = null;

        // --- 30 ejemplos de secuencias de factura ---
        const ejemplosSecuencia = [
            'FACT-', 'INV-', 'NK-', 'KIKA-', 'COMPRA-',
            'FAC-2024-', 'INV-2024-', 'ORD-', 'PED-', 'VENTA-',
            'CLIENTE-', 'C-', 'F-', 'OC-', 'SO-',
            'FACTURA-', 'NOTA-', 'RECIBO-', 'TICKET-', 'PAGO-',
            'FACT-NK-', 'INV-NK-', 'KIKA24-', 'NK2024-', 'COMP-',
            'FAC-NOV-', 'INV-NOV-', 'ORD-NOV-', 'PED-NOV-', 'VENT-NOV-'
        ];

        // --- Plantillas de factura mejoradas con más diferencias ---
        const plantillasFactura = {
            plantilla1: {
                nombre: "Clásica",
                descripcion: "Diseño simple y profesional con colores azules y tabla estándar",
                colores: {
                    primary: "#2563b0",
                    secondary: "#0a1628",
                    text: "#111827",
                    background: "#ffffff",
                    tableHeader: "#2563b0",
                    tableText: "#111827",
                    tableBorder: "#e5e7eb",
                    footer: "#6b7280"
                },
                logoPosition: { x: 20, y: 20, width: 40, height: 20 },
                titlePosition: { x: 105, y: 25 },
                tableStartY: 80,
                estilo: "estandar",
                showBorders: true,
                borderColor: "#e5e7eb",
                borderWidth: 0.5
            },
            plantilla2: {
                nombre: "Moderna",
                descripcion: "Diseño con colores vibrantes, tabla con bordes redondeados y fondo claro",
                colores: {
                    primary: "#059669",
                    secondary: "#052e16",
                    text: "#064e3b",
                    background: "#f8fafc",
                    tableHeader: "#059669",
                    tableText: "#064e3b",
                    tableBorder: "#e5e7eb",
                    footer: "#064e3b"
                },
                logoPosition: { x: 20, y: 20, width: 40, height: 20 },
                titlePosition: { x: 105, y: 25 },
                tableStartY: 80,
                estilo: "moderno",
                showBorders: true,
                borderColor: "#059669",
                borderWidth: 1,
                borderRadius: 5
            },
            plantilla3: {
                nombre: "Elegante",
                descripcion: "Diseño minimalista con tonos morados y sin bordes en la tabla",
                colores: {
                    primary: "#7c3aed",
                    secondary: "#311d4f",
                    text: "#4c1d95",
                    background: "#ffffff",
                    tableHeader: "#7c3aed",
                    tableText: "#4c1d95",
                    tableBorder: "#ffffff",
                    footer: "#7c3aed"
                },
                logoPosition: { x: 20, y: 20, width: 40, height: 20 },
                titlePosition: { x: 105, y: 25 },
                tableStartY: 80,
                estilo: "minimalista",
                showBorders: false,
                borderColor: "#ffffff",
                borderWidth: 0
            },
            plantilla4: {
                nombre: "Profesional",
                descripcion: "Diseño formal para negocios con estilo corporativo y bordes gruesos",
                colores: {
                    primary: "#1e4d8c",
                    secondary: "#0a1628",
                    text: "#111827",
                    background: "#ffffff",
                    tableHeader: "#1e4d8c",
                    tableText: "#111827",
                    tableBorder: "#374151",
                    footer: "#374151"
                },
                logoPosition: { x: 15, y: 15, width: 50, height: 25 },
                titlePosition: { x: 105, y: 30 },
                tableStartY: 90,
                estilo: "corporativo",
                showBorders: true,
                borderColor: "#374151",
                borderWidth: 1.5
            },
            plantilla5: {
                nombre: "Colorida",
                descripcion: "Diseño con múltiples colores, tabla con colores alternados en filas",
                colores: {
                    primary: "#f59e0b",
                    secondary: "#431407",
                    text: "#782911",
                    background: "#ffffff",
                    tableHeader: "#f59e0b",
                    tableText: "#782911",
                    tableBorder: "#fbbf24",
                    footer: "#d97706",
                    rowColors: ["#fef3c7", "#ffffff"]
                },
                logoPosition: { x: 20, y: 20, width: 40, height: 20 },
                titlePosition: { x: 105, y: 25 },
                tableStartY: 80,
                estilo: "colorido",
                showBorders: true,
                borderColor: "#fbbf24",
                borderWidth: 1
            },
            plantilla6: {
                nombre: "Clásica con Bordes",
                descripcion: "Diseño clásico con bordes destacados y fondo gris claro",
                colores: {
                    primary: "#2563b0",
                    secondary: "#0a1628",
                    text: "#111827",
                    background: "#f8f9fa",
                    tableHeader: "#2563b0",
                    tableText: "#111827",
                    tableBorder: "#9ca3af",
                    footer: "#4b5563"
                },
                logoPosition: { x: 20, y: 20, width: 40, height: 20 },
                titlePosition: { x: 105, y: 25 },
                tableStartY: 80,
                estilo: "bordes",
                showBorders: true,
                borderColor: "#9ca3af",
                borderWidth: 1
            },
            plantilla7: {
                nombre: "Minimalista",
                descripcion: "Diseño limpio y minimalista con espacio en blanco y sin bordes",
                colores: {
                    primary: "#374151",
                    secondary: "#111827",
                    text: "#111827",
                    background: "#ffffff",
                    tableHeader: "#374151",
                    tableText: "#111827",
                    tableBorder: "#ffffff",
                    footer: "#6b7280"
                },
                logoPosition: { x: 20, y: 20, width: 30, height: 15 },
                titlePosition: { x: 105, y: 20 },
                tableStartY: 70,
                estilo: "ultra-minimalista",
                showBorders: false,
                borderColor: "#ffffff",
                borderWidth: 0
            },
            plantilla8: {
                nombre: "Corporativa",
                descripcion: "Diseño corporativo con encabezado y pie de página destacados",
                colores: {
                    primary: "#1e40af",
                    secondary: "#1e3a8a",
                    text: "#1e40af",
                    background: "#ffffff",
                    tableHeader: "#1e40af",
                    tableText: "#1e40af",
                    tableBorder: "#1e40af",
                    footer: "#1e40af"
                },
                logoPosition: { x: 15, y: 15, width: 60, height: 30 },
                titlePosition: { x: 105, y: 35 },
                tableStartY: 100,
                estilo: "corporativa",
                showBorders: true,
                borderColor: "#1e40af",
                borderWidth: 2
            }
        };

        // --- Colores para ruletas ---
        const coloresRuleta = [
            '#2563b0', '#059669', '#7c3aed', '#dc2626', '#d97706',
            '#db2777', '#ca8a04', '#0891b2', '#1e40af', '#10b981',
            '#3b82f6', '#8b5cf6', '#ef4444', '#f59e0b', '#ec4899'
        ];

        // --- Diccionarios de idiomas ---
        const idiomas = {
            es: {
                txtTitulo: "Novedades Kika",
                txtSubtitulo: "Plataforma de registro y compra de productos para empleados. [Versión 9.0]",
                txtModoOscuro: "Modo Oscuro",
                txtModoClaro: "Modo Claro",
                txtCargar: "Cargar",
                txtGuardar: "Guardar",
                txtAyuda: "Ayuda",
                txtLogistica: "Logística",
                txtCompras: "Realizar Compra",
                txtRifaCompartidas: "Ruleta Compartidas",
                txtRifaCompras: "Ruleta Compras",
                txtResumenCompradoras: "Resumen",
                txtCuenta: "Cuenta",
                txtDashboard: "Dashboard",
                txtAjustes: "Ajustes",
                txtTituloLogistica: "Logística: Registro de Productos",
                txtNombreProducto: "Nombre del Producto",
                txtPrecioUnitario: "Precio Unitario",
                txtPrecioCosto: "Precio de Costo",
                txtCantidadProducto: "Cantidad",
                txtTamanoProducto: "Tamaño del Producto",
                txtSeleccioneTamano: "Seleccione un tamaño",
                txtTamanoPequeno: "Pequeño",
                txtTamanoMediano: "Mediano",
                txtTamanoGrande: "Grande",
                txtEspecificacionesProducto: "Especificaciones (ej: rojo, azul)",
                txtAgregarProducto: "Agregar Producto",
                txtBuscarProducto: "Buscar",
                txtProductosEnLogistica: "Productos en Logística",
                txtNombreTabla: "Nombre",
                txtPrecioUnitarioTabla: "Precio Unit.",
                txtPrecioCostoTabla: "Precio Costo",
                txtCantidadTabla: "Cantidad",
                txtStockTabla: "Stock",
                txtTamanoTabla: "Tamaño",
                txtCategoriaTabla: "Categoría",
                txtGananciaTabla: "Ganancia",
                txtEspecificacionesTabla: "Especificaciones",
                txtAccionesTabla: "Acciones",
                txtTotalGanancias: "Total Ganancias",
                txtTotalInversion: "Total Inversión",
                txtGastosExtra: "Gastos Extra",
                txtTotalProductos: "Total Productos",
                txtValorSobrante: "Valor Sobrante",
                txtStockBajo: "Stock Bajo",
                txtTituloCompras: "Realizar Compra",
                txtNombreComprador: "Nombre del Comprador",
                txtSeleccionarProducto: "Seleccionar Producto",
                txtSeleccioneProducto: "Seleccione un producto",
                txtNingunaEspecificacion: "(ninguna)",
                txtEspecificacionCompra: "Especificación",
                txtCantidadCompra: "Cantidad",
                txtAgregarCompra: "Agregar Compra",
                txtAgregarRegalo: "Agregar Regalo",
                txtCompradoresYCompras: "Compradores y sus Compras",
                txtTotalVentas: "Total de Ventas:",
                txtBuscarComprasProducto: "Buscar Compras por Producto",
                txtTituloResumenCompradoras: "Resumen de Compradoras",
                txtMarcados: "Marcados:",
                txtNoMarcados: "No Marcados:",
                txtFaltantes: "Faltantes:",
                txtMostrarNoMarcados: "Mostrar solo no marcados",
                txtMarcarResumen: "Marcar",
                txtCompradoraResumen: "Compradora",
                txtTotalDineroResumen: "Total en Dinero",
                txtTotalProductosResumen: "Total Productos",
                txtTamanoBolsaResumen: "Tamaño Bolsa",
                txtMejorResumen: "Mejor",
                txtCuentaDescargadaResumen: "Cuenta Descargada",
                txtAccionesResumen: "Acciones",
                txtTituloRifaCompartidas: "Ruleta Compartidas",
                txtAgregarParticipante: "Agregar",
                txtGana: "Gana",
                txtPierde: "Pierde",
                txtLimpiarRifa: "Limpiar Ruleta",
                txtTituloRifaCompras: "Ruleta Compras",
                txtGiraGana: "Gira Gana",
                txtGiraPierde: "Gira Pierde",
                txtLimpiarRifaCompras: "Limpiar Ruleta",
                txtTituloCuenta: "Cuenta de Compradoras",
                txtListaCompradoras: "Lista de Compradoras",
                txtNombreCompradora: "Nombre",
                txtTotalGastado: "Total Gastado",
                txtCuentaDescargada: "Cuenta Descargada",
                txtAccionesCuenta: "Acciones",
                txtTituloAjustes: "Ajustes",
                txtIdioma: "Idioma",
                txtEspañol: "Español",
                txtIngles: "English",
                txtFrances: "Français",
                txtLogoHeader: "Logo del Header",
                txtSeleccionarLogo: "Seleccionar Logo",
                txtCargarLogo: "Cargar Logo",
                txtBorrarTodo: "Borrar Todo",
                txtZonaPeligro: "Zona de Peligro",
                txtPedidosTiempoReal: "Pedidos en Tiempo Real",
                txtCerrarHDMI: "Cerrar",
                txtDescargarCuenta: "Descargar Cuenta",
                txtCompleteCampos: "Complete todos los campos correctamente.",
                txtNombreProductoEnUso: "El nombre del producto ya está en uso.",
                txtStockInsuficiente: "Stock insuficiente.",
                txtPrecioCostoInvalido: "El precio de costo no puede ser negativo.",
                txtPrecioUnitarioInvalido: "El precio unitario debe ser un número positivo.",
                txtPrecioCostoNegativo: "El precio de costo no puede ser negativo.",
                txtCantidadInvalida: "La cantidad debe ser un número positivo.",
                txtTamanoRequerido: "Seleccione un tamaño.",
                txtGananciaNegativaAdvertencia: "⚠️ La ganancia calculada es negativa. El costo supera los ingresos totales.\n¿Desea continuar de todas formas? Los números se mostrarán en rojo.",
                txtIngreseNombreComprador: "Ingrese el nombre del comprador.",
                txtIngreseProducto: "Seleccione un producto.",
                txtCantidadRequerida: "La cantidad es obligatoria y debe ser mayor a 0.",
                txtNoComprasProducto: "No se encontraron compras para este producto.",
                txtComprasPara: "Compras para",
                txtCompradores: "Compradores",
                txtTotalVendidos: "Total vendidos",
                txtInventarioOriginal: "Inventario original",
                txtSobrante: "Sobrante",
                txtValorSobranteLabel: "Valor del sobrante",
                txtIngreseNombreCompradora: "Ingrese el nombre de la compradora.",
                txtNoComprasCompradora: "No se encontraron compras para esta compradora.",
                txtCuentaYaGenerada: "La cuenta de esta compradora ya ha sido generada. ¿Desea generarla de nuevo?",
                txtSi: "Sí",
                txtNo: "No",
                txtConfirmarEliminarProducto: "¿Eliminar este producto?",
                txtConfirmarEliminarRegalo: "¿Está seguro de eliminar este regalo?",
                txtConfirmarEliminarCuenta: "¿Desea eliminar la cuenta de",
                txtConfirmarEliminarParticipante: "¿Eliminar participante?",
                txtConfirmarLimpiarRuleta: "¿Limpiar ruleta?",
                txtConfirmarLimpiarRuletaCompras: "¿Limpiar ruleta de compras?",
                txtConfirmarBorrarTodo: "¿Está seguro de borrar TODOS los datos? Esta acción no se puede deshacer.",
                txtNoParticipantesRuleta: "No hay participantes en la ruleta.",
                txtEditarParticipante: "Editar participante:",
                txtLogoCargado: "Logo cargado con éxito",
                txtSeleccioneArchivoImagen: "Por favor seleccione un archivo de imagen.",
                txtDatosCargados: "Datos cargados con éxito",
                txtEstructuraArchivoInvalida: "Estructura de archivo inválida",
                txtErrorCargarArchivo: "Error al cargar el archivo:",
                txtArchivoGenerado: "Archivo JSON generado con éxito",
                txtDatosBorrados: "Todos los datos han sido borrados.",
                txtEditar: "Editar",
                txtEliminar: "Eliminar",
                txtCancelar: "Cancelar",
                txtRedescargar: "Redescargar",
                txtDescargar: "Descargar",
                txtGanadorRuleta: "¡GANADOR!",
                txtPierdeRuleta: "PIERDE",
                txtFelicidades: "¡FELICIDADES!",
                txtSigueParticipando: "Sigue participando",
                txtTituloDashboard: "Dashboard",
                txtTotalVentasDashboard: "Ventas Totales",
                txtProductosVendidos: "Productos Vendidos",
                txtCompradoresActivos: "Compradores Activos",
                txtProductoMasVendido: "Producto Más Vendido",
                txtStockMinimo: "Stock Mínimo",
                txtCategoriaProducto: "Categoría",
                txtNotasCompra: "Notas",
                txtSeleccionarPlantilla: "Seleccionar Plantilla",
                txtVerPlantillas: "Ver Plantillas",
                txtBackupAuto: "Backup Automático",
                txtRealizarBackup: "Realizar Backup",
                txtRestaurarBackup: "Restaurar Backup",
                txtConfigurarSecuencia: "Configurar Secuencia",
                txtSecuenciaFactura: "Secuencia de Factura",
                txtEjemploSecuencia: "Ejemplo de secuencia",
                txtGuardarSecuencia: "Guardar Secuencia",
                txtEliminarSecuencia: "Eliminar Secuencia",
                txtSecuenciaGuardada: "Secuencia guardada correctamente",
                txtSecuenciaEliminada: "Secuencia eliminada correctamente",
                txtIngreseSecuencia: "Ingrese un prefijo para la secuencia de facturas",
                txtPersonalizarRuleta: "Personalizar Ruleta",
                txtColorRuleta: "Color de la ruleta"
            },
            en: {
                txtTitulo: "Novedades Kika",
                txtSubtitulo: "Purchase and registration platform for employees. [Version 9.0]",
                txtModoOscuro: "Dark Mode",
                txtModoClaro: "Light Mode",
                txtCargar: "Load",
                txtGuardar: "Save",
                txtAyuda: "Help",
                txtLogistica: "Logistics",
                txtCompras: "Make a Purchase",
                txtRifaCompartidas: "Shared Raffle",
                txtRifaCompras: "Purchases Raffle",
                txtResumenCompradoras: "Summary",
                txtCuenta: "Invoice",
                txtDashboard: "Dashboard",
                txtAjustes: "Settings",
                txtTituloLogistica: "Logistics: Product Registration",
                txtNombreProducto: "Product Name",
                txtPrecioUnitario: "Unit Price",
                txtPrecioCosto: "Cost Price",
                txtCantidadProducto: "Quantity",
                txtTamanoProducto: "Product Size",
                txtSeleccioneTamano: "Select a size",
                txtTamanoPequeno: "Small",
                txtTamanoMediano: "Medium",
                txtTamanoGrande: "Large",
                txtEspecificacionesProducto: "Specifications (e.g: red, blue)",
                txtAgregarProducto: "Add Product",
                txtBuscarProducto: "Search",
                txtProductosEnLogistica: "Products in Logistics",
                txtNombreTabla: "Name",
                txtPrecioUnitarioTabla: "Unit Price",
                txtPrecioCostoTabla: "Cost Price",
                txtCantidadTabla: "Quantity",
                txtStockTabla: "Stock",
                txtTamanoTabla: "Size",
                txtCategoriaTabla: "Category",
                txtGananciaTabla: "Profit",
                txtEspecificacionesTabla: "Specifications",
                txtAccionesTabla: "Actions",
                txtTotalGanancias: "Total Profits",
                txtTotalInversion: "Total Investment",
                txtGastosExtra: "Extra Expenses",
                txtTotalProductos: "Total Products",
                txtValorSobrante: "Surplus Value",
                txtStockBajo: "Low Stock",
                txtTituloCompras: "Make a Purchase",
                txtNombreComprador: "Buyer's Name",
                txtSeleccionarProducto: "Select Product",
                txtSeleccioneProducto: "Select a product",
                txtNingunaEspecificacion: "(none)",
                txtEspecificacionCompra: "Specification",
                txtCantidadCompra: "Quantity",
                txtAgregarCompra: "Add Purchase",
                txtAgregarRegalo: "Add Gift",
                txtCompradoresYCompras: "Buyers and their Purchases",
                txtTotalVentas: "Total Sales:",
                txtBuscarComprasProducto: "Search Purchases by Product",
                txtTituloResumenCompradoras: "Buyers Summary",
                txtMarcados: "Marked:",
                txtNoMarcados: "Unmarked:",
                txtFaltantes: "Missing:",
                txtMostrarNoMarcados: "Show only unmarked",
                txtMarcarResumen: "Mark",
                txtCompradoraResumen: "Buyer",
                txtTotalDineroResumen: "Total Money",
                txtTotalProductosResumen: "Total Products",
                txtTamanoBolsaResumen: "Bag Size",
                txtMejorResumen: "Best",
                txtCuentaDescargadaResumen: "Invoice Downloaded",
                txtAccionesResumen: "Actions",
                txtTituloRifaCompartidas: "Shared Raffle",
                txtAgregarParticipante: "Add",
                txtGana: "Wins",
                txtPierde: "Loses",
                txtLimpiarRifa: "Clear Raffle",
                txtTituloRifaCompras: "Purchases Raffle",
                txtGiraGana: "Spin Win",
                txtGiraPierde: "Spin Lose",
                txtLimpiarRifaCompras: "Clear Raffle",
                txtTituloCuenta: "Buyers' Invoices",
                txtListaCompradoras: "Buyers List",
                txtNombreCompradora: "Name",
                txtTotalGastado: "Total Spent",
                txtCuentaDescargada: "Invoice Downloaded",
                txtAccionesCuenta: "Actions",
                txtTituloAjustes: "Settings",
                txtIdioma: "Language",
                txtEspañol: "Spanish",
                txtIngles: "English",
                txtFrances: "French",
                txtLogoHeader: "Header Logo",
                txtSeleccionarLogo: "Select Logo",
                txtCargarLogo: "Load Logo",
                txtBorrarTodo: "Delete All",
                txtZonaPeligro: "Danger Zone",
                txtPedidosTiempoReal: "Real-Time Orders",
                txtCerrarHDMI: "Close",
                txtDescargarCuenta: "Download Invoice",
                txtCompleteCampos: "Complete all fields correctly.",
                txtNombreProductoEnUso: "The product name is already in use.",
                txtStockInsuficiente: "Insufficient stock.",
                txtPrecioCostoInvalido: "Cost price cannot be negative.",
                txtPrecioUnitarioInvalido: "Unit price must be a positive number.",
                txtPrecioCostoNegativo: "Cost price cannot be negative.",
                txtCantidadInvalida: "Quantity must be a positive number.",
                txtTamanoRequerido: "Please select a size.",
                txtGananciaNegativaAdvertencia: "⚠️ The calculated profit is negative. The cost exceeds total revenue.\nDo you want to continue anyway? Numbers will be shown in red.",
                txtIngreseNombreComprador: "Enter the buyer's name.",
                txtIngreseProducto: "Select a product.",
                txtCantidadRequerida: "Quantity is required and must be greater than 0.",
                txtNoComprasProducto: "No purchases found for this product.",
                txtComprasPara: "Purchases for",
                txtCompradores: "Buyers",
                txtTotalVendidos: "Total sold",
                txtInventarioOriginal: "Original inventory",
                txtSobrante: "Surplus",
                txtValorSobranteLabel: "Surplus value",
                txtIngreseNombreCompradora: "Enter the buyer's name.",
                txtNoComprasCompradora: "No purchases found for this buyer.",
                txtCuentaYaGenerada: "This buyer's invoice has already been generated. Do you want to generate it again?",
                txtSi: "Yes",
                txtNo: "No",
                txtConfirmarEliminarProducto: "Delete this product?",
                txtConfirmarEliminarRegalo: "Are you sure you want to delete this gift?",
                txtConfirmarEliminarCuenta: "Do you want to delete the invoice of",
                txtConfirmarEliminarParticipante: "Delete participant?",
                txtConfirmarLimpiarRuleta: "Clear raffle?",
                txtConfirmarLimpiarRuletaCompras: "Clear purchases raffle?",
                txtConfirmarBorrarTodo: "Are you sure you want to delete ALL data? This action cannot be undone.",
                txtNoParticipantesRuleta: "There are no participants in the raffle.",
                txtEditarParticipante: "Edit participant:",
                txtLogoCargado: "Logo loaded successfully",
                txtSeleccioneArchivoImagen: "Please select an image file.",
                txtDatosCargados: "Data loaded successfully",
                txtEstructuraArchivoInvalida: "Invalid file structure",
                txtErrorCargarArchivo: "Error loading file:",
                txtArchivoGenerado: "JSON file generated successfully",
                txtDatosBorrados: "All data has been deleted.",
                txtEditar: "Edit",
                txtEliminar: "Delete",
                txtCancelar: "Cancel",
                txtRedescargar: "Redownload",
                txtDescargar: "Download",
                txtGanadorRuleta: "WINNER!",
                txtPierdeRuleta: "LOSES",
                txtFelicidades: "CONGRATULATIONS!",
                txtSigueParticipando: "Keep trying",
                txtTituloDashboard: "Dashboard",
                txtTotalVentasDashboard: "Total Sales",
                txtProductosVendidos: "Products Sold",
                txtCompradoresActivos: "Active Buyers",
                txtProductoMasVendido: "Best Selling Product",
                txtStockMinimo: "Minimum Stock",
                txtCategoriaProducto: "Category",
                txtNotasCompra: "Notes",
                txtSeleccionarPlantilla: "Select Template",
                txtVerPlantillas: "View Templates",
                txtBackupAuto: "Automatic Backup",
                txtRealizarBackup: "Perform Backup",
                txtRestaurarBackup: "Restore Backup",
                txtConfigurarSecuencia: "Configure Sequence",
                txtSecuenciaFactura: "Invoice Sequence",
                txtEjemploSecuencia: "Sequence Example",
                txtGuardarSecuencia: "Save Sequence",
                txtEliminarSecuencia: "Delete Sequence",
                txtSecuenciaGuardada: "Sequence saved successfully",
                txtSecuenciaEliminada: "Sequence deleted successfully",
                txtIngreseSecuencia: "Enter a prefix for the invoice sequence",
                txtPersonalizarRuleta: "Customize Raffle",
                txtColorRuleta: "Raffle color"
            },
            fr: {
                txtTitulo: "Novedades Kika",
                txtSubtitulo: "Plateforme d'achat et d'enregistrement pour les employés. [Version 9.0]",
                txtModoOscuro: "Mode Sombre",
                txtModoClaro: "Mode Clair",
                txtCargar: "Charger",
                txtGuardar: "Sauvegarder",
                txtAyuda: "Aide",
                txtLogistica: "Logistique",
                txtCompras: "Effectuer un Achat",
                txtRifaCompartidas: "Tombola Partagée",
                txtRifaCompras: "Tombola des Achats",
                txtResumenCompradoras: "Résumé",
                txtCuenta: "Facture",
                txtDashboard: "Tableau de bord",
                txtAjustes: "Réglages",
                txtTituloLogistica: "Logistique : Enregistrement des Produits",
                txtNombreProducto: "Nom du Produit",
                txtPrecioUnitario: "Prix Unitaire",
                txtPrecioCosto: "Prix de Coût",
                txtCantidadProducto: "Quantité",
                txtTamanoProducto: "Taille du Produit",
                txtSeleccioneTamano: "Sélectionnez une taille",
                txtTamanoPequeno: "Petit",
                txtTamanoMediano: "Moyen",
                txtTamanoGrande: "Grand",
                txtEspecificacionesProducto: "Spécifications (ex: rouge, bleu)",
                txtAgregarProducto: "Ajouter un Produit",
                txtBuscarProducto: "Rechercher",
                txtProductosEnLogistica: "Produits en Logistique",
                txtNombreTabla: "Nom",
                txtPrecioUnitarioTabla: "Prix Unitaire",
                txtPrecioCostoTabla: "Prix de Coût",
                txtCantidadTabla: "Quantité",
                txtStockTabla: "Stock",
                txtTamanoTabla: "Taille",
                txtCategoriaTabla: "Catégorie",
                txtGananciaTabla: "Profit",
                txtEspecificacionesTabla: "Spécifications",
                txtAccionesTabla: "Actions",
                txtTotalGanancias: "Total des Gains",
                txtTotalInversion: "Investissement Total",
                txtGastosExtra: "Dépenses Supp.",
                txtTotalProductos: "Total des Produits",
                txtValorSobrante: "Valeur du Surplus",
                txtStockBajo: "Stock Faible",
                txtTituloCompras: "Effectuer un Achat",
                txtNombreComprador: "Nom de l'Acheteur",
                txtSeleccionarProducto: "Sélectionner un Produit",
                txtSeleccioneProducto: "Sélectionnez un produit",
                txtNingunaEspecificacion: "(aucun)",
                txtEspecificacionCompra: "Spécification",
                txtCantidadCompra: "Quantité",
                txtAgregarCompra: "Ajouter un Achat",
                txtAgregarRegalo: "Ajouter un Cadeau",
                txtCompradoresYCompras: "Acheteurs et leurs Achats",
                txtTotalVentas: "Ventes Totales :",
                txtBuscarComprasProducto: "Rechercher les Achats par Produit",
                txtTituloResumenCompradoras: "Résumé des Acheteurs",
                txtMarcados: "Marqués :",
                txtNoMarcados: "Non marqués :",
                txtFaltantes: "Manquants :",
                txtMostrarNoMarcados: "Afficher uniquement les non marqués",
                txtMarcarResumen: "Marquer",
                txtCompradoraResumen: "Acheteur",
                txtTotalDineroResumen: "Total en Argent",
                txtTotalProductosResumen: "Total des Produits",
                txtTamanoBolsaResumen: "Taille du Sac",
                txtMejorResumen: "Meilleur",
                txtCuentaDescargadaResumen: "Facture Téléchargée",
                txtAccionesResumen: "Actions",
                txtTituloRifaCompartidas: "Tombola Partagée",
                txtAgregarParticipante: "Ajouter",
                txtGana: "Gagne",
                txtPierde: "Perd",
                txtLimpiarRifa: "Effacer la Tombola",
                txtTituloRifaCompras: "Tombola des Achats",
                txtGiraGana: "Tour Gagnant",
                txtGiraPierde: "Tour Perdant",
                txtLimpiarRifaCompras: "Effacer la Tombola",
                txtTituloCuenta: "Factures des Acheteurs",
                txtListaCompradoras: "Liste des Acheteurs",
                txtNombreCompradora: "Nom",
                txtTotalGastado: "Total Dépensé",
                txtCuentaDescargada: "Facture Téléchargée",
                txtAccionesCuenta: "Actions",
                txtTituloAjustes: "Réglages",
                txtIdioma: "Langue",
                txtEspañol: "Espagnol",
                txtIngles: "Anglais",
                txtFrances: "Français",
                txtLogoHeader: "Logo de l'En-tête",
                txtSeleccionarLogo: "Sélectionner un Logo",
                txtCargarLogo: "Charger le Logo",
                txtBorrarTodo: "Tout Supprimer",
                txtZonaPeligro: "Zone de Danger",
                txtPedidosTiempoReal: "Commandes en Temps Réel",
                txtCerrarHDMI: "Fermer",
                txtDescargarCuenta: "Télécharger Facture",
                txtCompleteCampos: "Veuillez remplir tous les champs correctement.",
                txtNombreProductoEnUso: "Le nom du produit est déjà utilisé.",
                txtStockInsuficiente: "Stock insuffisant.",
                txtPrecioCostoInvalido: "Le prix de coût ne peut pas être négatif.",
                txtPrecioUnitarioInvalido: "Le prix unitaire doit être un nombre positif.",
                txtPrecioCostoNegativo: "Le prix de coût ne peut pas être négatif.",
                txtCantidadInvalida: "La quantité doit être un nombre positif.",
                txtTamanoRequerido: "Veuillez sélectionner une taille.",
                txtGananciaNegativaAdvertencia: "⚠️ Le bénéfice calculé est négatif. Le coût dépasse les revenus totaux.\nVoulez-vous continuer quand même ? Les chiffres apparaîtront en rouge.",
                txtIngreseNombreComprador: "Veuillez entrer le nom de l'acheteur.",
                txtIngreseProducto: "Veuillez sélectionner un produit.",
                txtCantidadRequerida: "La quantité est obligatoire et doit être supérieure à 0.",
                txtNoComprasProducto: "Aucun achat trouvé pour ce produit.",
                txtComprasPara: "Achats pour",
                txtCompradores: "Acheteurs",
                txtTotalVendidos: "Total vendu",
                txtInventarioOriginal: "Stock initial",
                txtSobrante: "Surplus",
                txtValorSobranteLabel: "Valeur du surplus",
                txtIngreseNombreCompradora: "Veuillez entrer le nom de l'acheteur.",
                txtNoComprasCompradora: "Aucun achat trouvé pour cet acheteur.",
                txtCuentaYaGenerada: "La facture de cet acheteur a déjà été générée. Voulez-vous la regénérer ?",
                txtSi: "Oui",
                txtNo: "Non",
                txtConfirmarEliminarProducto: "Supprimer ce produit ?",
                txtConfirmarEliminarRegalo: "Êtes-vous sûr de vouloir supprimer ce cadeau ?",
                txtConfirmarEliminarCuenta: "Voulez-vous supprimer la facture de",
                txtConfirmarEliminarParticipante: "Supprimer le participant ?",
                txtConfirmarLimpiarRuleta: "Effacer la tombola ?",
                txtConfirmarLimpiarRuletaCompras: "Effacer la tombola des achats ?",
                txtConfirmarBorrarTodo: "Êtes-vous sûr de vouloir supprimer TOUTES les données ? Cette action ne peut pas être annulée.",
                txtNoParticipantesRuleta: "Il n'y a pas de participants dans la tombola.",
                txtEditarParticipante: "Modifier le participant :",
                txtLogoCargado: "Logo chargé avec succès",
                txtSeleccioneArchivoImagen: "Veuillez sélectionner un fichier image.",
                txtDatosCargados: "Données chargées avec succès",
                txtEstructuraArchivoInvalida: "Structure de fichier invalide",
                txtErrorCargarArchivo: "Erreur lors du chargement du fichier :",
                txtArchivoGenerado: "Fichier JSON généré avec succès",
                txtDatosBorrados: "Toutes les données ont été supprimées.",
                txtEditar: "Modifier",
                txtEliminar: "Supprimer",
                txtCancelar: "Annuler",
                txtRedescargar: "Télécharger à nouveau",
                txtDescargar: "Télécharger",
                txtGanadorRuleta: "GAGNANT!",
                txtPierdeRuleta: "PERD",
                txtFelicidades: "FÉLICITATIONS!",
                txtSigueParticipando: "Continuez à participer",
                txtTituloDashboard: "Tableau de bord",
                txtTotalVentasDashboard: "Ventes Totales",
                txtProductosVendidos: "Produits Vendus",
                txtCompradoresActivos: "Acheteurs Actifs",
                txtProductoMasVendido: "Produit le Plus Vendu",
                txtStockMinimo: "Stock Minimum",
                txtCategoriaProducto: "Catégorie",
                txtNotasCompra: "Notes",
                txtSeleccionarPlantilla: "Sélectionner un Modèle",
                txtVerPlantillas: "Voir les Modèles",
                txtBackupAuto: "Sauvegarde Automatique",
                txtRealizarBackup: "Effectuer une Sauvegarde",
                txtRestaurarBackup: "Restaurer la Sauvegarde",
                txtConfigurarSecuencia: "Configurer la Séquence",
                txtSecuenciaFactura: "Séquence de Facture",
                txtEjemploSecuencia: "Exemple de Séquence",
                txtGuardarSecuencia: "Sauvegarder la Séquence",
                txtEliminarSecuencia: "Supprimer la Séquence",
                txtSecuenciaGuardada: "Séquence sauvegardée avec succès",
                txtSecuenciaEliminada: "Séquence supprimée avec succès",
                txtIngreseSecuencia: "Entrez un préfixe pour la séquence de factures",
                txtPersonalizarRuleta: "Personnaliser la Tombola",
                txtColorRuleta: "Couleur de la tombola"
            }
        };

        // --- Inicialización de IndexedDB ---
